#!/usr/bin/env python3
"""Regenerate the Cursor and Codex adapters from the canonical SKILL.md.

Single source of truth: SKILL.md. The adapters are DERIVED — never hand-edit them.
Run:  python build.py          regenerate both adapters
      python build.py --check  write nothing; exit 1 if the adapters drifted from SKILL.md
No third-party dependencies; standard library only.
"""

import argparse
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SKILL = ROOT / "SKILL.md"
ADAPTERS = ROOT / "adapters"
CURSOR = ADAPTERS / "cursor-dependency-first-architect.mdc"
CODEX = ADAPTERS / "AGENTS.md"

# Shared sentinel from SKILL.md that must survive into both adapters.
SENTINEL = "Tradeoff gates"

# The adapters get copied into other people's repos (Codex appends to their AGENTS.md), so the
# banner must make sense there too, and BEGIN/END let an installed copy be replaced cleanly.
BANNER_LINES = [
    "BEGIN dependency-first-architect — GENERATED FILE, DO NOT HAND-EDIT.",
    "Generated by build.py from SKILL.md in https://github.com/NiravRVaghasiya/dependency-first-architect",
    "To update, re-run the install command from that README (in AGENTS.md: replace BEGIN to END).",
]
END_MARKER = "<!-- END dependency-first-architect -->"


def parse_skill(text):
    """Split SKILL.md into (frontmatter_dict, description, body_markdown)."""
    if not text.startswith("---"):
        raise ValueError("SKILL.md must start with YAML frontmatter delimited by ---")
    parts = text.split("---", 2)
    # parts[0] == "" , parts[1] == frontmatter , parts[2] == body
    front_raw = parts[1]
    body = parts[2].lstrip("\n")

    name = ""
    description = ""
    # Minimal frontmatter parse: support `key: value` and a `description: >-` block.
    lines = front_raw.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip().startswith("name:"):
            name = line.split(":", 1)[1].strip()
            i += 1
        elif line.strip().startswith("description:"):
            after = line.split(":", 1)[1].strip()
            if after in (">-", ">", "|", "|-", "|+"):
                # Folded/literal block: collect indented following lines.
                i += 1
                block = []
                while i < len(lines) and (lines[i].startswith("  ") or not lines[i].strip()):
                    if not lines[i].strip():
                        i += 1
                        continue
                    block.append(lines[i].strip())
                    i += 1
                description = " ".join(block).strip()
            else:
                description = after
                i += 1
        else:
            i += 1

    if not name:
        raise ValueError("frontmatter missing `name`")
    if not description:
        raise ValueError("frontmatter missing `description`")
    return name, description, body


def banner(comment_prefix):
    return "\n".join(f"{comment_prefix} {line}" for line in BANNER_LINES)


def build_cursor(name, description, body):
    """Cursor .mdc: YAML frontmatter with alwaysApply:false + an HTML-comment banner."""
    fm = [
        "---",
        f"description: {description}",
        "globs:",
        "alwaysApply: false",
        "---",
    ]
    head = "\n".join(fm)
    note = f"<!--\n{banner('')}\n-->".replace("\n \n", "\n\n")
    return f"{head}\n\n{note}\n\n{body.rstrip()}\n\n{END_MARKER}\n"


def build_codex(name, description, body):
    """Codex AGENTS.md: plain markdown, banner as an HTML comment, trigger stated inline."""
    note = f"<!--\n" + "\n".join(BANNER_LINES) + "\n-->"
    header = f"# {name}\n\n**When to use:** {description}"
    return f"{note}\n\n{header}\n\n{body.rstrip()}\n\n{END_MARKER}\n"


def render():
    """Generate both adapters in memory from SKILL.md: {path: content}."""
    name, description, body = parse_skill(SKILL.read_text(encoding="utf-8"))
    return {
        CURSOR: build_cursor(name, description, body),
        CODEX: build_codex(name, description, body),
    }


def find_drift(outputs):
    """Diff each generated adapter against the file on disk; return the paths that differ."""
    drifted = []
    for path, expected in outputs.items():
        rel = path.relative_to(ROOT).as_posix()
        if not path.exists():
            print(f"DRIFT: {rel} is missing")
            drifted.append(path)
            continue
        # read_text() turns CRLF into LF, so a Windows checkout of identical content is not
        # drift; any real content change is.
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            sys.stdout.writelines(difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{rel} (committed)",
                tofile=f"{rel} (generated from SKILL.md)",
            ))
            drifted.append(path)
    return drifted


def main(argv=None):
    parser = argparse.ArgumentParser(description="Regenerate the adapters from SKILL.md.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if either adapter differs from what SKILL.md generates",
    )
    args = parser.parse_args(argv)

    # Diffs contain non-ASCII (—, →); emit UTF-8 rather than e.g. cp1252 on Windows pipes.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")

    outputs = render()

    # Sanity: the shared sentinel from SKILL.md must survive into both adapters.
    for path, out in outputs.items():
        if SENTINEL not in out:
            print(f"ERROR: sentinel '{SENTINEL}' missing from {path.name}", file=sys.stderr)
            return 1

    if args.check:
        drifted = find_drift(outputs)
        if drifted:
            print(
                f"\nERROR: {len(drifted)} adapter(s) out of sync with SKILL.md. "
                "Run `python build.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        for path in outputs:
            print(f"In sync: {path.relative_to(ROOT).as_posix()}")
        print(f"Sentinel '{SENTINEL}' present in SKILL.md and both adapters: OK")
        return 0

    ADAPTERS.mkdir(exist_ok=True)
    for path, out in outputs.items():
        # Write bytes so the output is LF on every OS (text mode emits CRLF on Windows).
        path.write_bytes(out.encode("utf-8"))
        print(f"Generated {path.relative_to(ROOT)}")
    print(f"Sentinel '{SENTINEL}' present in SKILL.md and both adapters: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
