"""Tests for eval/dfa_eval/report.py: REPORT.md generated from summary.json alone.

Standard library only:  python -m unittest discover -s tests -v
"""

import math
import re
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "eval"))
sys.path.insert(0, str(ROOT / "tests" / "fixtures"))
from dfa_eval import aggregate, records, report  # noqa: E402
import runbuilder as rb  # noqa: E402
from fixture_runs import contrast_run, rich_run, small_run  # noqa: E402

RANKING = re.compile(r"\b(?:winner|best|beats|proves)\b", re.I)
SECTIONS = ["## What was run", "## How to read this", "## Results by condition", "## Contrasts",
            "## Length and efficiency", "## Judge reliability", "## Leakage probe",
            "## Per-prompt cells", "## Flags"]
T975_2 = 4.302652729911275


def row(text, *starts):
    """The table row that starts with the given cells."""
    prefix = "| " + " | ".join(starts) + " |"
    hits = [line for line in text.splitlines() if line.startswith(prefix)]
    if len(hits) != 1:
        raise AssertionError(f"expected one row starting {prefix!r}, found {len(hits)}")
    return hits[0]


class ReportFromRunTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.tmp = Path(tempfile.mkdtemp())
        cls.addClassCleanup(shutil.rmtree, cls.tmp)
        cls.run_dir = contrast_run(cls.tmp)
        aggregate.write_summary(cls.run_dir)
        cls.text = report.write_report(cls.run_dir)

    def test_header_sections_and_trailing_newline(self):
        lines = self.text.split("\n")
        self.assertEqual(lines[0], report.HEADER)
        self.assertEqual(lines[0], "<!-- GENERATED by eval/dfa_eval/report.py from summary.json "
                                   "— do not hand-edit -->")
        positions = [self.text.index("\n" + s + "\n") for s in SECTIONS]
        self.assertEqual(positions, sorted(positions))
        self.assertTrue(self.text.endswith("\n") and not self.text.endswith("\n\n"))
        self.assertNotIn("\r", self.text)

    def test_deterministic(self):
        summary = records.read_json(self.run_dir / "summary.json")
        manifest = records.read_json(self.run_dir / "manifest.json")
        self.assertEqual(report.render_report(summary, manifest), self.text)
        self.assertEqual((self.run_dir / "REPORT.md").read_bytes(), self.text.encode("utf-8"))

    def test_no_ranking_words_and_no_p_values(self):
        self.assertIsNone(RANKING.search(self.text), RANKING.search(self.text))
        self.assertNotRegex(self.text, r"\bp\s*[<=]\s*0?\.\d")
        self.assertIn("no p-values and no rankings", self.text)

    def test_what_was_run(self):
        for expected in ("**Benchmark:** fixture-bench — Fixture benchmark.",
                         "created 2026-10-02", "harness 1.0.0; skill 2.0.0; repo commit abc1234",
                         "3 prompts × 2 conditions × 1 generator(s); 2 run(s) per cell",
                         "| generator | g1 | fake | gen-model |", "| judge | j1 | fake | judge-model |",
                         "| dfa | skill | dependency-first-architect | — | The Dependency-First "
                         "Architect skill. |",
                         "| P1 | AI | RAG support chatbot | Plan a customer-support RAG chatbot over "
                         "our help-center docs. |",
                         "**Total cost:** $0.96 over 48 records"):  # 0.90 + 24 x 0.002 + 12 x 0.001
            self.assertIn(expected, self.text)
        self.assertNotIn("superseded", self.text)  # no record was replaced by a retry

    def test_number_formats(self):
        # /20 and /44 scores: 1 decimal; 0-1 scores: 2 decimals; words: integers; USD: 2 decimals.
        dfa = row(self.text, "dfa", "g1", "3", "6")
        half = 4.302652729911275 * 50 / math.sqrt(3)  # words: prompt means 320, 270, 370
        for cell in ("20.0 ± 0.0 [20.0, 20.0]", "32.0 ± 5.0 [19.6, 44.4]",
                     "1.00 ± 0.00 [1.00, 1.00]",
                     f"320 ± 50 [{320 - half:.0f}, {320 + half:.0f}]",
                     "0.10 ± 0.00 [0.10, 0.10]"):
            self.assertIn(f"| {cell} |", dfa)
        eq = row(self.text, "dfa − baseline", "g1", "EQ")
        self.assertIn("| +8.0 | [0.5, 15.5] |", eq)
        self.assertIn("| 2.67 | 3.48 | 1.00 | 3 (6 / 6) |", eq)
        adherence = row(self.text, "dfa − baseline", "g1", "adherence")
        self.assertIn("| n/a | n/a | 1.00 |", adherence)  # dz and g undefined
        self.assertIn("ceiling: 100% of treatment generations at max", adherence)
        words = row(self.text, "dfa − baseline", "g1", "words")
        self.assertIn("| +80 |", words)
        lint = row(self.text, "dfa − baseline", "g1", "lint")
        self.assertIn("| +0.75 | [0.75, 0.75] |", lint)

    def test_reliability_leakage_and_flags(self):
        self.assertIn("| methodology-adherence-v1 | 1 | 0 | n/a | n/a | n/a | j1 16.0 (n=12) |",
                      self.text)
        self.assertIn("| j1 | g1 | skill conditions vs plain conditions | 12 (6 / 6) | 0.86 |", self.text)
        self.assertIn("0.5 = judges cannot tell", self.text)
        self.assertIn("- small n: 3 prompt(s) (< 5): intervals across prompts are wide", self.text)

    def test_generated_from_summary_and_manifest_only(self):
        copy = self.tmp / "only-summary" / self.run_dir.name
        copy.mkdir(parents=True)
        for name in ("summary.json", "manifest.json"):
            shutil.copyfile(self.run_dir / name, copy / name)
        self.assertEqual(report.write_report(copy), self.text)


class CheckReportTest(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp)
        self.run_dir = small_run(self.tmp)

    def test_check_detects_missing_stale_and_edited_reports(self):
        ok, diff = report.check_report(self.run_dir)
        self.assertFalse(ok)
        self.assertIn("summary.json is missing", diff)
        aggregate.write_summary(self.run_dir)
        ok, diff = report.check_report(self.run_dir)
        self.assertFalse(ok)
        self.assertIn("REPORT.md is missing", diff)
        text = report.write_report(self.run_dir)
        self.assertEqual(report.check_report(self.run_dir), (True, ""))
        path = self.run_dir / "REPORT.md"
        path.write_bytes(text.replace("\n", "\r\n").encode("utf-8"))  # CRLF checkout: no drift
        self.assertEqual(report.check_report(self.run_dir), (True, ""))
        path.write_bytes(text.replace("## Flags", "## Flags\n\nhand edit").encode("utf-8"))
        ok, diff = report.check_report(self.run_dir)
        self.assertFalse(ok)
        self.assertIn("REPORT.md (committed)", diff)
        self.assertIn("-hand edit", diff)
        # A changed summary makes the committed report stale.
        report.write_report(self.run_dir)
        summary = records.read_json(self.run_dir / "summary.json")
        summary["flags"].append("a new flag")
        records.write_json(self.run_dir / "summary.json", summary)
        ok, diff = report.check_report(self.run_dir)
        self.assertFalse(ok)
        self.assertIn("+- a new flag", diff)


class EdgeCaseReportsTest(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.tmp)

    def test_rich_run_report(self):
        run_dir = rich_run(self.tmp)
        aggregate.write_summary(run_dir)
        text = report.write_report(run_dir)
        self.assertIsNone(RANKING.search(text))
        self.assertIn("missing an arm on: P2", text)
        self.assertIn("judge model also generated these plans", text)
        self.assertIn("| dfa-capped | g1 | 4 |", text)
        self.assertIn("| 100 | 0.75 (3 of 4) |", text)  # cap and compliance
        self.assertIn("| P2 | generic-control | g1 | 0 | 2 | n/a |", text)
        self.assertIn("- excluded 3 generation(s) with status error", text)
        self.assertIn("$0.74 over 173 records", text)
        self.assertIn("3 record(s) with unknown cost are not included", text)

    def test_cost_of_records_replaced_by_a_retry_is_reported(self):
        run_dir = small_run(self.tmp)
        rb.supersede(run_dir, run_dir / "generations" / "P1.dfa.g1.r01.json", status="error",
                     error="fixture: the CLI exited 1", output_file=None, output_sha256=None,
                     metrics=None, cost_usd=0.5)
        aggregate.write_summary(run_dir)
        text = report.write_report(run_dir)
        # 4 x 0.01 + 8 x 0.002 + 0.50, over 4 + 8 + 1 records: the parts add up to the total.
        self.assertIn("**Total cost:** $0.56 over 13 records (generation $0.04, judging $0.02, "
                      "probes $0.00, superseded by a retry $0.50 over 1 record(s); a judgment "
                      "retried after an invalid reply is one record with the cost of every "
                      "attempt); 0 record(s) with unknown cost are not included", text)
        self.assertEqual(report.check_report(run_dir), (True, ""))

    def test_sparse_run_report(self):
        gens = [rb.gen("P1", "dfa", 1), rb.gen("P1", "baseline", 1)]
        run_dir = rb.make_run(self.tmp, gens, prompts=("P1",), runs_per_cell=1, write_lint=False,
                              contrasts=(), judges=[])
        aggregate.write_summary(run_dir)
        text = report.write_report(run_dir)
        self.assertIn("No contrasts were configured", text)
        self.assertIn("No probe was run.", text)
        self.assertIn("none (probe disabled)", text)
        self.assertIn("n/a", text)

    def test_ranking_words_in_config_text_are_removed(self):
        gens = [rb.gen(p, c, 1, adherence={"j1": 15}) for p in ("P1", "P2")
                for c in ("baseline", "dfa")]
        run_dir = rb.make_run(self.tmp, gens, runs_per_cell=1, rubrics=(rb.ADHERENCE,),
                              condition_overrides={"dfa": {
                                  "description": "The best planner | it beats the baseline, "
                                                 "proves it, and is the WINNER."}})
        aggregate.write_summary(run_dir)
        text = report.write_report(run_dir)
        self.assertIsNone(RANKING.search(text), RANKING.search(text))
        self.assertIn("The […] planner \\| it […] the baseline, […] it, and is the […].", text)

    def test_ranking_words_in_summary_text_are_removed(self):
        run_dir = small_run(self.tmp)
        summary = aggregate.write_summary(run_dir)
        manifest = records.read_json(run_dir / "manifest.json")
        summary["flags"].append("the best run; it beats the rest")
        summary["contrasts"][0]["notes"].append("proves the winner")
        summary["leakage"] = [{"judge": "j1", "n_probes": 0, "n_ok": 0, "note": "Best probe.",
                               "skill_vs_plain": {"n": 0, "n_positive": 0, "n_negative": 0,
                                                  "auc": None, "accuracy": None,
                                                  "accuracy_ci95": None},
                               "contrasts": []}]
        text = report.render_report(summary, manifest)
        self.assertIsNone(RANKING.search(text), RANKING.search(text))
        self.assertIn("- the […] run; it […] the rest", text)

    def test_signs_and_zero(self):
        self.assertEqual(report._signed(-0.04, 1), "0.0")
        self.assertEqual(report._signed(0.04, 1), "0.0")
        self.assertEqual(report._signed(1.26, 1), "+1.3")
        self.assertEqual(report._signed(-2.0, 2), "-2.00")
        self.assertEqual(report._num(-0.0001, 2), "0.00")
        self.assertEqual(report._num(None, 1), "n/a")
        self.assertEqual(report._interval(None, 1), "n/a")
        self.assertEqual(report._mean_sd_ci({"mean": 1.0, "sd": None, "ci95": None}, 1),
                         "1.0 ± n/a [n/a]")


if __name__ == "__main__":
    unittest.main()
