#!/usr/bin/env python3
"""Recompute every eval score in SCORECARD.md and the READMEs from the raw scores.

Input:  examples/scoring/judgments.json — 3 blind judges (and 3 adversarial auditors) per plan,
        10 plans, 10 rubric dimensions each. Produced by examples/scoring/run_eval.py.
        examples/scoring/generation.json — the SHA-256 of each plan as the model wrote it.
Run:    python examples/scoring/tally.py          rewrite the generated blocks
        python examples/scoring/tally.py --check  write nothing; exit 1 if a block is stale
Both modes fail if a committed plan no longer matches the model output it was scored on.
Standard library only.
"""

import argparse
import hashlib
import json
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
JUDGMENTS = HERE / "judgments.json"
GENERATION = HERE / "generation.json"
SCORECARD = HERE.parent / "SCORECARD.md"
README = ROOT / "README.md"
EXAMPLES_README = HERE.parent / "README.md"
BEGIN_TABLES = "<!-- BEGIN GENERATED by examples/scoring/tally.py — do not hand-edit -->"
BEGIN_CALLOUT = "<!-- BEGIN GENERATED score callout: examples/scoring/tally.py -->"
BEGIN_INDEX = "<!-- BEGIN GENERATED examples index: examples/scoring/tally.py -->"
END = "<!-- END GENERATED -->"
SHIP = 16  # reference/evals.md: >=16 ship
D9 = 8  # zero-based index of D9, AI layer correctness
HEADER_END = "\n\n---\n\n"  # ends the provenance header on each example plan
ARMS = ("without", "with")


def medians(rows):
    """Per-dimension median of 3 integer rows (always an integer 0-2)."""
    return [int(statistics.median(column)) for column in zip(*rows)]


def signed(value):
    return f"{value:+.1f}" if isinstance(value, float) else f"{value:+d}"


class Tally:
    def __init__(self, data):
        self.dims = data["dimensions"]
        self.plan = {(p["prompt"], p["arm"]): p for p in data["plans"]}
        self.prompts = sorted({p["prompt"] for p in data["plans"]})
        self.med = {k: medians([j["scores"] for j in p["judges"]]) for k, p in self.plan.items()}
        self.total = {k: sum(row) for k, row in self.med.items()}
        self.delta = {pid: self.total[(pid, "with")] - self.total[(pid, "without")]
                      for pid in self.prompts}
        self.mean = {arm: statistics.fmean(self.total[(pid, arm)] for pid in self.prompts)
                     for arm in ARMS}
        self.mean_delta = self.mean["with"] - self.mean["without"]
        self.audited = None
        if all("audit" in p for p in data["plans"]):
            proposals = {k: [a["proposed"] for a in p["audit"]["auditors"]]
                         for k, p in self.plan.items()}
            # "majority": the median auditor per dimension. "any": every single dispute stands
            # (skeptics can only lower, advocates can only raise, so that is min / max).
            self.audited = {
                "majority": {k: medians(rows) for k, rows in proposals.items()},
                "any": {k: [(min if k[1] == "with" else max)(col) for col in zip(*rows)]
                        for k, rows in proposals.items()},
            }
            self.bound = {
                rule: {pid: sum(scores[(pid, "with")]) - sum(scores[(pid, "without")])
                       for pid in self.prompts}
                for rule, scores in self.audited.items()
            }
            self.mean_bound = {rule: statistics.fmean(b.values()) for rule, b in self.bound.items()}
            # Floor: every dispute accepted AND D9 dropped on non-AI prompts (the rubric artifact).
            any_ = self.audited["any"]
            self.floor = statistics.fmean(
                self.bound["any"][pid]
                - ((any_[(pid, "with")][D9] - any_[(pid, "without")][D9])
                   if self.plan[(pid, "without")]["kind"] != "AI" else 0)
                for pid in self.prompts
            )


def render_tables(t):
    out = ["### Totals (/20, per-dimension median of 3 blind judges)", ""]
    out += ["| Prompt | Without skill | With skill | Delta |", "|---|---:|---:|---:|"]
    for pid in t.prompts:
        w, s = t.plan[(pid, "without")], t.plan[(pid, "with")]
        out.append(
            f"| {pid} {w['title']} ({w['kind']}) | [{t.total[(pid, 'without')]}]({w['file']}) "
            f"| [{t.total[(pid, 'with')]}]({s['file']}) | **{signed(t.delta[pid])}** |"
        )
    out.append(f"| **Mean** | **{t.mean['without']:.1f}** | **{t.mean['with']:.1f}** "
               f"| **{signed(t.mean_delta)}** |")

    out += ["", "### Per-dimension medians (0 absent · 1 partial · 2 done well)", ""]
    out.append("| Plan | " + " | ".join(f"D{i}" for i in range(1, len(t.dims) + 1)) + " | Total |")
    out.append("|---|" + "---:|" * (len(t.dims) + 1))
    for pid in t.prompts:
        for arm in ARMS:
            row = t.med[(pid, arm)]
            out.append(f"| {pid} {arm} | " + " | ".join(map(str, row)) + f" | {sum(row)} |")
    for arm in ARMS:
        cols = [statistics.fmean(t.med[(pid, arm)][i] for pid in t.prompts)
                for i in range(len(t.dims))]
        out.append(f"| *mean {arm}* | " + " | ".join(f"*{c:.1f}*" for c in cols)
                   + f" | *{t.mean[arm]:.1f}* |")
    out += ["", " · ".join(f"**D{i}** {name}" for i, name in enumerate(t.dims, 1))]

    out += ["", "### Judge agreement (each judge's own total)", ""]
    out += ["| Plan | Judge 1 | Judge 2 | Judge 3 | Spread |", "|---|---:|---:|---:|---:|"]
    for pid in t.prompts:
        for arm in ARMS:
            totals = [sum(j["scores"]) for j in t.plan[(pid, arm)]["judges"]]
            out.append(f"| {pid} {arm} | " + " | ".join(map(str, totals))
                       + f" | {max(totals) - min(totals)} |")

    out += ["", f"### Below the ship bar ({SHIP}/20), with the weakest dimension", ""]
    out.append("Weakest = lowest median; ties broken by the lowest mean across the 3 judges. "
               "On non-AI prompts D9 is left out of the pick (see the sensitivity note below).")
    out += ["", "| Plan | Total | Weakest dimension (median, judge mean) |", "|---|---:|---|"]
    below = 0
    for pid in t.prompts:
        for arm in ARMS:
            row = t.med[(pid, arm)]
            if sum(row) >= SHIP:
                continue
            below += 1
            judges = t.plan[(pid, arm)]["judges"]
            means = [statistics.fmean(col) for col in zip(*(j["scores"] for j in judges))]
            non_ai = t.plan[(pid, arm)]["kind"] != "AI"
            pool = [i for i in range(len(row)) if not (non_ai and i == D9)]
            low = min((row[i], means[i]) for i in pool)
            weakest = ", ".join(f"D{i + 1} {t.dims[i]} ({row[i]}, {means[i]:.2f})"
                                for i in pool if (row[i], means[i]) == low)
            if non_ai and row[D9] == 0:
                weakest += "; D9 is also 0"
            out.append(f"| {pid} {arm} | {sum(row)} | {weakest} |")
    if not below:
        out.append("| none | | |")

    # Rubric artifact: D9 gives a non-AI plan 2 only if it explicitly declares the AI layer N/A.
    non_ai = [pid for pid in t.prompts if t.plan[(pid, "without")]["kind"] != "AI"]
    gain = {pid: t.med[(pid, "with")][D9] - t.med[(pid, "without")][D9] for pid in non_ai}
    adjusted = statistics.fmean(t.delta[pid] - gain.get(pid, 0) for pid in t.prompts)
    out += ["", "### Sensitivity: D9 on non-AI prompts", ""]
    out.append(
        f"On the non-AI prompts ({', '.join(non_ai)}), D9 accounts for {sum(gain.values())} of "
        f"their {sum(t.delta[pid] for pid in non_ai)} delta points. Excluding D9 for those "
        f"prompts, the mean delta is **{signed(adjusted)}** (vs {signed(t.mean_delta)} with it). "
        f"Per prompt: " + ", ".join(f"{pid} {signed(t.delta[pid] - gain.get(pid, 0))}"
                                    for pid in t.prompts) + "."
    )

    if t.audited:
        out += ["", "### Adversarial audit: the skill-unfavorable bound", ""]
        out.append("Three skeptics per with-skill plan could only lower scores; three advocates "
                   "per plan without the skill could only raise them. *Majority*: each "
                   "dimension takes the median auditor. *Any dispute*: every change proposed by "
                   "even one auditor is accepted.")
        out += ["", "| Prompt | Without: judged → majority → any | With: judged → majority → any "
                "| Delta: judged → majority → any |", "|---|---:|---:|---:|"]
        for pid in t.prompts:
            cells = []
            for arm in ARMS:
                cells.append(" → ".join(str(sum(s)) for s in (
                    t.med[(pid, arm)], t.audited["majority"][(pid, arm)],
                    t.audited["any"][(pid, arm)])))
            deltas = " → ".join([signed(t.delta[pid]), signed(t.bound["majority"][pid]),
                                 f"**{signed(t.bound['any'][pid])}**"])
            out.append(f"| {pid} | {cells[0]} | {cells[1]} | {deltas} |")
        out.append(f"| **Mean** | | | {signed(t.mean_delta)} → "
                   f"{signed(t.mean_bound['majority'])} → **{signed(t.mean_bound['any'])}** |")
        disputes = [f"{pid} {arm} D{i} {before}→{after} (auditor {a['auditor']})"
                    for pid in t.prompts for arm in ARMS
                    for a in t.plan[(pid, arm)]["audit"]["auditors"]
                    for i, (before, after) in enumerate(zip(t.med[(pid, arm)], a["proposed"]), 1)
                    if before != after]
        out += ["", "Every individual dispute: " + ("; ".join(disputes) or "none") + "."]
        out += ["", f"**Floor.** Accept every dispute *and* drop D9 on the non-AI prompts: the "
                f"mean delta is **{signed(t.floor)}**. This is a deliberately skill-unfavorable "
                f"reading of the audit; it still counts each dimension's median judge."]

    out += ["", "### Plan length (words, model output only)", ""]
    out += ["| Prompt | Without skill | With skill |", "|---|---:|---:|"]
    for pid in t.prompts:
        out.append(f"| {pid} | {words(t.plan[(pid, 'without')])} | {words(t.plan[(pid, 'with')])} |")

    out += ["", "### Self-score (claimed by the with-skill plan) vs judged", ""]
    out += ["| Plan | Self-score | Judged | Gap |", "|---|---:|---:|---:|"]
    for pid in t.prompts:
        claimed = t.plan[(pid, "with")].get("self_score")
        judged = t.total[(pid, "with")]
        shown = "n/a" if claimed is None else claimed
        gap = "n/a" if claimed is None else signed(judged - claimed)
        out.append(f"| {pid} with | {shown} | {judged} | {gap} |")
    return "\n".join(out) + "\n"


def words(plan):
    """Word count of the model's output (the example file minus its provenance header)."""
    text = (HERE.parent / plan["file"]).read_text(encoding="utf-8")
    return len(text.split(HEADER_END, 1)[1].split())


def render_index(t):
    out = ["| Prompt | Without the skill | With the skill | Delta |", "|---|---:|---:|---:|"]
    for pid in t.prompts:
        w, s = t.plan[(pid, "without")], t.plan[(pid, "with")]
        out.append(f"| **{pid}** {w['title']} | [{t.total[(pid, 'without')]}/20]({w['file']}) "
                   f"| [{t.total[(pid, 'with')]}/20]({s['file']}) | {signed(t.delta[pid])} |")
    out.append(f"| **Mean** | {t.mean['without']:.1f} | {t.mean['with']:.1f} "
               f"| {signed(t.mean_delta)} |")
    return "\n".join(out) + "\n"


def render_callout(t):
    text = (
        f"> **Measured, not claimed.** In Claude Code, same model, the 5 fixed prompts in "
        f"[`reference/evals.md`](reference/evals.md), one run per arm, each plan blind-scored "
        f"by 3 independent judges: **{t.mean['without']:.1f}/20 without the skill → "
        f"{t.mean['with']:.1f}/20 with it ({signed(t.mean_delta)})**."
    )
    if t.audited:
        still = " still" if t.floor > 0 else ""
        text += (f" On a deliberately skill-unfavorable reading (every dispute from an "
                 f"adversarial audit accepted, and the D9 rubric artifact removed), the lift "
                 f"is{still} **{signed(t.floor)}**.")
    return text + " [Scorecard, method and raw scores →](examples/SCORECARD.md)\n"


def splice(doc, begin, block, name):
    head, found, rest = doc.partition(begin)
    _, found_end, tail = rest.partition(END)
    if not found or not found_end:
        raise SystemExit(f"ERROR: {name} is missing its generated-block markers")
    return f"{head}{begin}\n{block}{END}{tail}"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Rebuild eval numbers from the raw scores.")
    parser.add_argument("--check", action="store_true", help="exit 1 if a file is stale")
    args = parser.parse_args(argv)
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")

    # The scores only mean something for the exact text that was scored.
    tampered = 0
    for run in json.loads(GENERATION.read_text(encoding="utf-8"))["runs"]:
        path = next(HERE.parent.glob(f"{run['prompt'].lower()}-*/{run['arm']}-skill.md"))
        body = path.read_text(encoding="utf-8").split(HEADER_END, 1)[1]
        if hashlib.sha256(body.encode("utf-8")).hexdigest() != run["sha256"]:
            print(f"ERROR: {path.relative_to(ROOT).as_posix()} differs from the model output "
                  f"it was scored on", file=sys.stderr)
            tampered += 1
    if tampered:
        return 1

    t = Tally(json.loads(JUDGMENTS.read_text(encoding="utf-8")))
    targets = [
        (SCORECARD, BEGIN_TABLES, "\n" + render_tables(t) + "\n"),
        (README, BEGIN_CALLOUT, render_callout(t)),
        (EXAMPLES_README, BEGIN_INDEX, render_index(t)),
    ]
    stale = 0
    for path, begin, block in targets:
        name = path.relative_to(ROOT).as_posix()
        updated = splice(path.read_text(encoding="utf-8"), begin, block, name)
        current = path.read_text(encoding="utf-8")
        if args.check:
            if updated != current:
                print(f"ERROR: {name} does not match judgments.json", file=sys.stderr)
                stale += 1
            else:
                print(f"{name} matches judgments.json: OK")
        elif updated != current:
            path.write_bytes(updated.encode("utf-8"))
            print(f"Updated {name}")
    if stale:
        print("Run `python examples/scoring/tally.py` and commit the result.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
